<?php
/*
Plugin Name: Dojo Rank Board
Plugin URI: http://tampaaikido.com/
Description: A 'nafudakake' is a traditional Japanese name slat board, where members of a martial art school (Karate, Judo, Aikido, etc.) have their names displayed in order of seniority and divided by rank.  This plugin generates an easily-managed and attractive virtual nafudakake which can be displayed using a widget or a shortcode.
Version: 2.01 11/14/2017
Author: Guy Hagen
Author URI: http://tampaaikido.com/
License: GPL2
*/

/* ###################################################################### */
/* Avoid direct file access to plugin files */
/* ###################################################################### */
if ( ! defined( 'ABSPATH' ) ) exit; 

/* ###################################################################### */
/* LINK LIBRARIES */
/* ###################################################################### */
require_once("code/admin.php");



/* ###################################################################### */
/* SETUP  */
/* ###################################################################### */

wpnafu_setupDefinitions(); 


function wpnafu_setupDefinitions()
{
	DEFINE('WPNAFU_DIRECTORY',plugin_dir_path( __FILE__ ));
	DEFINE('WPNAFU_URL',plugin_dir_url( __FILE__ ));
	
	add_option("nafu_rowcount", 2);
	add_option("nafu_slatheight", 180);
	add_option("nafu_slatwidth", 18);
	add_option("nafu_fontsize", 1);
	add_option("nafu_showtooltip", "No");
	add_option("nafu_layouttype", "Horizontal");
	add_option("nafu_slatspacing", 2);
}
 



/* ###################################################################### */
/* SHORTCODES AND PUBLIC FUNCTIONS */
/* ###################################################################### */

function wpnafu_tooltip()
{
	$o=' <div class="nafu_tooltip">What is this?
  <span class="nafu_tooltiptext"><p style="margin-bottom:12px;">In many traditional Aikido, Karate, Judo, Kendo, Jujitsu and other Japanese martial art schools, a <a href="https://en.wikipedia.org/wiki/Nafudakake"><em>nafudakake</em></a> is a wooden board that displays the names and ranks of the members.</p><p>Our rank board is generated by the <a href="http://tampaaikido.com/resources/wp-nafudakake/">Rank Board Plugin for Wordpress</a>, and developed by the <a href="http://tampaaikido.com">Aikido Chuseikan Dojo of Tampa Bay</a>.</p></span></div>';
	return $o;

}

function wpnafu_shortcode($atts)
{
	global $wpdb; 
	
	$rcount=intval(get_option("nafu_rowcount"));
	$saveRows=get_option("nafu_saveRows");
	$saveClasses=get_option("nafu_saveClasses");
	$saveContents=get_option("nafu_saveContents");
	$orientation=get_option("nafu_layouttype");
	$itemcount=sizeof($saveContents); 
	
	$o.='<div id="rank_board">';
	
	$currow=0;
	 
	 //------------------------------------------------------------------
	 //fill out rows with items in them from last edit
	for ($i=0; $i<$itemcount; $i++)
	{
		$thisContent=stripslashes($saveContents[$i]);
		$thisRow=intval($saveRows[$i]);
		$thisClass=($saveClasses[$i]);   
		
		if ($thisRow > $currow) // HTML break new row
			{
				if ($currow >0) // must end previous row
				{
					$o.="</ul></div>\r\n";
				}
				
				// begin new row
				$o.='<div>';
				$o.='<ul id="slatrow'.$thisRow.'" class="';
				
				if ($orientation=="Vertical") {$o.="rank_row_vertical"; }
				//else  {$o.=" rank_row_horizontal"; }
				$o.='">'."\r\n";
			
				$currow=$thisRow;			
			}
			
			//Now print this slat
			$o.='<li class="'.$thisClass.'"><div class="nafu_orientation">'. $thisContent .'</div></li>'."\r\n";
 
		
		} // end 
	
		if ($currow >0) // must end previous row
		{
			// close off final row and table tag
			$o.="\r\n
			</ul>\r\n
			</div>\r\n";
		}
		
	$o.="</div>";// rank_board
	
	if (get_option("nafu_showtooltip")=="Yes") { $o.=wpnafu_tooltip(); }
	
	$o.="<script defer>
		var nafu_slatheight=".get_option("nafu_slatheight").";
		var nafu_slatwidth=".get_option("nafu_slatwidth").";
		var nafu_slatspacing=".(get_option("nafu_slatspacing")+0).";
		var nafu_fontsize=".(get_option("nafu_fontsize")+0).";
		var nafu_layouttype='".get_option("nafu_layouttype")."';</script>";
		
	return $o;
}

add_shortcode('rank_board', 'wpnafu_shortcode');
add_shortcode('rank-board', 'wpnafu_shortcode');
 
?>